"User vim configuration

"Vundle configuration-------------------------------------------------
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'scrooloose/nerdtree'

Plugin 'Xuyuanp/nerdtree-git-plugin'

call vundle#end()
filetype plugin indent on
"---------------------------------------------------------------------

"User functions

"Toggling relative numbering
function! ToggleRelativeNumbering()
    if(&relativenumber == 1)
        set norelativenumber
        set number
    else
        set relativenumber
    endif
endfunc

"Restoring cursor positions
function! ResCur()
    if line("'\"")<=line("$")
        normal! g`"
        return 1 
    endif
endfunction

augroup resCur
    autocmd!
    autocmd BufWinEnter * call ResCur()
augroup END

"Plugin specific

"NERDTree configurations --------------------------------------------------------------------------------------------------
"Toggle NERDTree
nnoremap <leader>nt :NERDTreeToggle<CR>
"
"Ignoring files
let NERDTreeIgnore = ['\.pyc$']

"Open split to the right and bottom
set splitright
set splitbelow

autocmd vimenter * NERDTree

"Close vim if the only window left open is NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

"NERDTree configuration ends ----------------------------------------------------------------------------------------------

" Colorscheme
syntax enable
colorscheme monokai

"Set line numbering
set number

"Set line number width
let line_number_width=3
execute "set numberwidth=".line_number_width

"Text wrap column size
set textwidth=200

"Set tab spacing
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

"Highlight current line
set cursorline

"Visual autocomplete for command menu
set wildmenu

"Redraw only when we need to
set lazyredraw

"Highlight matching braces
set showmatch 

"Search as characters are entered
set incsearch

"Highlight matches
set nohlsearch

"Set leader key
let mapleader=","

"Enabling backup
set backup
set backupdir=~/.vim/.backup//
set directory=~/.vim/.swap//
set writebackup

"Saving previous file cursor location and buffers
set viminfo='10,\"100,:20,%,n~/.viminfo

"Setting fold options
set foldmethod=marker

"Remaps

"Saving file
nnoremap <leader>w :w<CR>

"Closing file
nnoremap <leader>q :q<CR>

"Sourcing vimrc
nnoremap <leader>so :source $MYVIMRC<CR>

"Saving file and sourcing
nnoremap <leader>sso :w<CR> :source $MYVIMRC<CR>

"Save session
nnoremap <leader>s :mksession ~/.vim/sessions/current.vim<CR>

"Remaps to function calls

"Calling toggle relative numbering
nnoremap <c-t> :call ToggleRelativeNumbering()<CR> 

"Enter a new line and move to normal mode
nnoremap oo o<Esc>

"Insert a line above and move to normal mode
nnoremap OO O<Esc>

"Activate window switching
nnoremap <leader>wi <c-w>

"Switch to specific window
nnoremap wh <c-w>h
nnoremap wl <c-w>l
nnoremap wj <c-w>j
nnoremap wk <c-w>k

"Scroll down 25 lines
nnoremap <leader>d 25<c-e>

"Scroll up 25 lines
nnoremap <leader>e 25<c-y>

"Move to the next tab. 'n' and 'p' are used as alt-h causes the help menu to open in GVim
nnoremap tl :tabn<CR>

"Move to the previous tab
nnoremap th :tabp<CR>

"Close tab
nnoremap tk :tabclose<CR>

"Open window in a new tab
nnoremap tj :tabedit %<CR>

"Open new tab
nnoremap tt :tabedit <CR>

"Switch to the next buffer
nnoremap <leader>bn :bn<CR>

"Switch to the previous buffer
nnoremap <leader>bp :bp<CR>

"Run python
autocmd FileType python nnoremap <buffer> <leader>b :exec '!clear; python' shellescape(@%, 1)<CR>

"Sourcing files and vimballs
"Source supertab
source ~/.vim/vimball/supertab.vmb




















